version: "3.7"
services:
    api-poi:
        build: "./backend"
        container_name: api-msarabando-container
        volumes:
            - ./backend:/home/node/app
        ports: 
            - "4000:4000"
        restart: always
    web:
        build: "./frontend"
        container_name: web-msarabando-container
        restart: always
        volumes:
            - ./frontend:/home/node/app
        ports: 
            - "3000:3000"
        depends_on: 
            - api-poi